# Site settings
title: Certbot
email: certbot@eff.org
description: > # this means to ignore newlines until "baseurl:"
  Certbot is the easiest way to enable HTTPS on your website through Let's Encrypt.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://certbot.eff.org" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
collections:
- faq_entries
exclude:
- README.md
- package.json
- node_modules
- gulpfile.js
keep_files:
- css
- js

# Build settings
markdown: kramdown
